# GROUP 08: META AI: BLECA BOOTCAMP
## PART A

In [1]:
import pandas as pd

headers = ['Name', 'ID', 'Age']
students = [
    ['Arafa Hashim', 23459, 21],
    ['Baraka Daudi', 78907, 22],
    ['Dinka Kaiza', 45678, 24],
    ['Gregory Bahati', 38921, 22],
    ['Ibrahim Emmanuel', 73217, 67]
]

data_frame = pd.DataFrame(students, columns=headers)
print(data_frame)

               Name     ID  Age
0      Arafa Hashim  23459   21
1      Baraka Daudi  78907   22
2       Dinka Kaiza  45678   24
3    Gregory Bahati  38921   22
4  Ibrahim Emmanuel  73217   67

In [2]:
import pandas as pd

students = {
    'Name' : ['Arafa Hashim', 'Baraka Daudi', 'Dinka Kaiza', 'Gregory Bahati', 'Ibrahim Emmanuel'],
    'ID' : [23459, 78907, 45678, 38921, 73217],
    'Age' : [21, 22, 24, 22, 67]
}

data_frame = pd.DataFrame(students)

print(data_frame)

print(data_frame.columns)

               Name     ID  Age
0      Arafa Hashim  23459   21
1      Baraka Daudi  78907   22
2       Dinka Kaiza  45678   24
3    Gregory Bahati  38921   22
4  Ibrahim Emmanuel  73217   67
Index(['Name', 'ID', 'Age'], dtype='object')

In [3]:
student_names = pd.Series(['Bernard Joseph', 'Chris Bwesa', 'Phocus', 'Fedelika', 'Ipyana Mwaisekwa'])
ages = pd.Series([32, 34, 26, 31, 45])
scores = pd.Series([80, 81, 79, 85, 83])

data_frame = pd.concat([student_names, ages, scores], axis=1)
data_frame.columns = ['Name', 'Age', 'Scores']
print(data_frame)

"""
The relationship between a series and a dataframe is that a dataframe is made up of multiple concatenated series 
combined together
"""

               Name  Age  Scores
0    Bernard Joseph   32      80
1       Chris Bwesa   34      81
2            Phocus   26      79
3          Fedelika   31      85
4  Ipyana Mwaisekwa   45      83

'\nThe relationship between a series and a dataframe is that a dataframe is made up of multiple concatenated series \ncombined together\n'

# PART B
## SPOTIFY SONG DATA SET

In [4]:
import pandas as pd

data_frame = pd.read_csv('spotify_tracks.csv')

print("-------------------- These are the first 10 records --------------------")
print(data_frame.head())
print("------------------------------------------------------------------------")

print("----------------------- Shapes of the dataframe ------------------------")
print(data_frame.shape)
print("------------------------------------------------------------------------")

print("---------------------- Column names and datatypes ----------------------")
print(data_frame.columns)

-------------------- These are the first 10 records --------------------
                       id                                           name  \
0  7kr3xZk4yb3YSZ4VFtg2Qt                                       Acoustic
1  1kJygfS4eoVziBBI93MSYp                                       Acoustic
2  6lynns69p4zTCRxmmiSY1x                  Here Comes the Sun - Acoustic
3  1RC9slv335IfLce5vt9KTW                                    Acoustic #3
4  5o9L8xBuILoVjLECSBi7Vo  My Love Mine All Mine - Acoustic Instrumental

      genre                        artists  \
0  acoustic                  Billy Raffoul
1  acoustic                  Billy Raffoul
2  acoustic  Molly Hocking, Bailey Rushlow
3  acoustic              The Goo Goo Dolls
4  acoustic  Guus Dielissen, Casper Esmann

                                           album  popularity  duration_ms  \
0                                           1975          58       172199
1                        A Few More Hours at YYZ          57       172202
2                  Here Comes the Sun (Acoustic)          42       144786
3                              Dizzy up the Girl          46       116573
4  My Love Mine All Mine (Acoustic Instrumental)          33       133922

   explicit
0     False
1     False
2     False
3     False
4     False
------------------------------------------------------------------------
----------------------- Shapes of the dataframe ------------------------
(6300, 8)
------------------------------------------------------------------------
---------------------- Column names and datatypes ----------------------
Index(['id', 'name', 'genre', 'artists', 'album', 'popularity', 'duration_ms',
       'explicit'],
      dtype='object')

In [5]:
import pandas as pd

data_frame = pd.read_csv('spotify_tracks.csv')

print(f"Average popularity is {data_frame['popularity'].mean()}")
print(f"Maximum popularity is {data_frame['popularity'].max()}")
print(f"Average duration is {data_frame['duration_ms'].mean()} ms")
print(f"Minimum duration is {data_frame['duration_ms'].min()} and Maximum duration is {data_frame['duration_ms'].max()}")

print("---------- DESCRIPTION OF THE DATA -------------")
print(data_frame.describe())

Average popularity is 30.754761904761907
Maximum popularity is 90
Average duration is 202847.73523809525 ms
Minimum duration is 30060 and Maximum duration is 3601658
---------- DESCRIPTION OF THE DATA -------------
        popularity   duration_ms
count  6300.000000  6.300000e+03
mean     30.754762  2.028477e+05
std      19.948991  1.210299e+05
min       0.000000  3.006000e+04
25%      16.000000  1.476870e+05
50%      29.000000  1.916070e+05
75%      45.000000  2.369625e+05
max      90.000000  3.601658e+06

In [6]:
import pandas as pd
data_frame = pd.read_csv('spotify_tracks.csv')

data_frame['duration_min'] = data_frame['duration_ms'] / 60000
print(data_frame)


data_frame.to_csv('spotify_tracks_minutes.csv', index=False)
print(data_frame.head())

                          id                                           name  \
0     7kr3xZk4yb3YSZ4VFtg2Qt                                       Acoustic
1     1kJygfS4eoVziBBI93MSYp                                       Acoustic
2     6lynns69p4zTCRxmmiSY1x                  Here Comes the Sun - Acoustic
3     1RC9slv335IfLce5vt9KTW                                    Acoustic #3
4     5o9L8xBuILoVjLECSBi7Vo  My Love Mine All Mine - Acoustic Instrumental
...                      ...                                            ...
6295  4uveHSzaz8YEbTF9j6QlCI                             Voyage to Atlantis
6296  4u15cjyziW2Ewn5Ek3082l                                       L'Oiseau
6297  56pHPaTeX2O9aVmTFYS8hV                                   The Daintree
6298  6Ldyc5TsR4kaUsuHKcB2AD                         The Sorcerers Symphony
6299  3ry0f8ybk8upUBIk8unvmF                                Fiore d'inverno

            genre                                     artists  \
0        acoustic                               Billy Raffoul
1        acoustic                               Billy Raffoul
2        acoustic               Molly Hocking, Bailey Rushlow
3        acoustic                           The Goo Goo Dolls
4        acoustic               Guus Dielissen, Casper Esmann
...           ...                                         ...
6295  world-music                          Future World Music
6296  world-music  Putumayo, Marianne Perrudin, Thomas Artaud
6297  world-music                             Joseph Tawadros
6298  world-music                          Future World Music
6299  world-music                  Putumayo, Giacomo Lariccia

                                              album  popularity  duration_ms  \
0                                              1975          58       172199
1                           A Few More Hours at YYZ          57       172202
2                     Here Comes the Sun (Acoustic)          42       144786
3                                 Dizzy up the Girl          46       116573
4     My Love Mine All Mine (Acoustic Instrumental)          33       133922
...                                             ...         ...          ...
6295                             Reign of Vengeance          25       180001
6296                  Global Relaxation by Putumayo          25       276776
6297                                    World Music          12        69533
6298                                         Behold          26        90001
6299                      World Party 5 by Putumayo          25       141800

      explicit  duration_min
0        False      2.869983
1        False      2.870033
2        False      2.413100
3        False      1.942883
4        False      2.232033
...        ...           ...
6295     False      3.000017
6296     False      4.612933
6297     False      1.158883
6298     False      1.500017
6299     False      2.363333

[6300 rows x 9 columns]
                       id                                           name  \
0  7kr3xZk4yb3YSZ4VFtg2Qt                                       Acoustic
1  1kJygfS4eoVziBBI93MSYp                                       Acoustic
2  6lynns69p4zTCRxmmiSY1x                  Here Comes the Sun - Acoustic
3  1RC9slv335IfLce5vt9KTW                                    Acoustic #3
4  5o9L8xBuILoVjLECSBi7Vo  My Love Mine All Mine - Acoustic Instrumental

      genre                        artists  \
0  acoustic                  Billy Raffoul
1  acoustic                  Billy Raffoul
2  acoustic  Molly Hocking, Bailey Rushlow
3  acoustic              The Goo Goo Dolls
4  acoustic  Guus Dielissen, Casper Esmann

                                           album  popularity  duration_ms  \
0                                           1975          58       172199
1                        A Few More Hours at YYZ          57       172202
2                  Here Comes the Sun (Acoustic)          42       144786
3                              Dizzy up the Girl          46       116573
4  My Love Mine All Mine (Acoustic Instrumental)          33       133922

   explicit  duration_min
0     False      2.869983
1     False      2.870033
2     False      2.413100
3     False      1.942883
4     False      2.232033

In [7]:
import pandas as pd
data_frame = pd.read_csv('spotify_tracks.csv')

long_tracks = data_frame[data_frame['popularity'] > 80]
print("------------- SONGS WITH POPULARITY > 80 ----------------")
display(long_tracks.head(10))

print("------------------------- EXPLICIT SONGS ----------------------")
display(data_frame[data_frame['explicit'] == True])

genres = data_frame['genre'].unique()   
choice = input("Which genre do you want?: ")
while(choice not in genres) :
    print(f"Available genres are {list(genres)}")
    choice = input("Genre is not available in the track, enter another one: ")
else :
    print(f"------------------------ 10 Songs of {choice} ----------------------------")
    display(data_frame[data_frame['genre'] == choice].head(10))

print("--------------------- 10 SONGS LONGER THAN AVERAGE DURATION ---------------------")
display(data_frame[data_frame['duration_ms'] > data_frame['duration_ms'].mean()].head(10))

------------- SONGS WITH POPULARITY > 80 ----------------

,id,name,genre,artists,album,popularity,duration_ms,explicit
1094,1zi7xx7UVEFkmKfv06H8x0,One Dance,dance,"Drake, Wizkid, Kyla",Views,82,173986,False
1096,4kbj5MwxO1bq9wjT5g9HaA,Shut Up and Dance,dance,WALK THE MOON,TALKING IS HARD,81,199080,False
1567,2HYFX63wP3otVIvopRS99Z,Houdini,edm,Eminem,Houdini,90,227239,True
1853,3B54sVLJ402zGa6Xm4YGNe,Unforgettable,french,"French Montana, Swae Lee",Jungle Rules,82,233901,True
2797,4Dvkj6JhhA12EX05fT7y2e,As It Was,house,Harry Styles,Harry's House,87,167303,False
2805,4uUG5RXrOk84mYEfFvj3cK,I'm Good (Blue),idm,"David Guetta, Bebe Rexha",I'm Good (Blue),83,175238,True
2816,0pqnGHJpmpxLKifKRmU6WP,Believer,idm,Imagine Dragons,Evolve,81,204346,False
3158,7CyPwkp0oE8Ro9Dd5CUDjW,"One Of The Girls (with JENNIE, Lily Rose Depp)",j-idol,"The Weeknd, JENNIE, Lily-Rose Depp",The Idol Episode 4 (Music from the HBO Origina...,87,244684,False
3160,6WzRpISELf3YglGAh7TXcG,Popular (with Playboi Carti & Madonna) - From ...,j-idol,"The Weeknd, Playboi Carti, Madonna",Popular (Music from the HBO Original Series),81,215466,True
3213,1aKvZDoLGkNMxoRYgkckZG,Magnetic,j-pop,ILLIT,SUPER REAL ME,86,160688,False

------------------------- EXPLICIT SONGS ----------------------

,id,name,genre,artists,album,popularity,duration_ms,explicit
33,6Ea2uAyHX6Q8DnGKrMKHLq,Inertia - Acoustic,acoustic,AJR,Inertia (Acoustic),58,230990,True
36,4qsRrKXNKBxZjKWHBrRdXs,Acoustic Levitation,acoustic,Devin The Dude,Acoustic Levitation,29,355961,True
39,5YABYtKx9qa56vBjlXDbmw,Snooze (Acoustic) (feat. Justin Bieber),acoustic,"SZA, Justin Bieber",Snooze (Acoustic) (feat. Justin Bieber),65,190464,True
44,0r5j1OxaqLkhxJOgA0kstj,Acoustic,acoustic,XtraVert,Acoustic,0,153012,True
50,6JZcfM5vr5O0KeGIAWiydu,Afrobeat 2023 Mixtape,afrobeat,Dj funkybee,Afrobeat 2023 Mixtape,28,3601658,True
...,...,...,...,...,...,...,...,...
6234,75TgpG1v6hOdXepZLjX962,Work Out,work-out,"BradBrooks, Pamela Bravo",Water Boy: Purple,12,105604,True
6239,1bL6yJplNtNPI5XAaqkLDi,Work It Out,work-out,"Lil Jon, Pitbull",Crunk Rock (Deluxe),25,223440,True
6242,2QnJdbQLPAw1xktGhshIB6,XXX,work-out,Kim Petras,Workout Playlist 2023,21,124285,True
6249,6F513WWSroMXL4TO9b2UdD,Work It Out,work-out,Ella,Make Way,18,176013,True
6266,4xmdscX2Uh00vE6w1svAsc,Jumentinho,world-music,"Nelsinho dos teclados, World Music Production",Jumentinho,24,185436,True

Available genres are ['acoustic', 'afrobeat', 'alt-rock', 'alternative', 'ambient', 'anime', 'black-metal', 'bluegrass', 'blues', 'bossanova', 'brazil', 'breakbeat', 'british', 'cantopop', 'chicago-house', 'children', 'chill', 'classical', 'club', 'comedy', 'country', 'dance', 'dancehall', 'death-metal', 'deep-house', 'detroit-techno', 'disco', 'disney', 'drum-and-bass', 'dub', 'dubstep', 'edm', 'electro', 'electronic', 'emo', 'folk', 'forro', 'french', 'funk', 'garage', 'german', 'gospel', 'goth', 'grindcore', 'groove', 'grunge', 'guitar', 'happy', 'hard-rock', 'hardcore', 'hardstyle', 'heavy-metal', 'hip-hop', 'holidays', 'honky-tonk', 'house', 'idm', 'indian', 'indie', 'indie-pop', 'industrial', 'iranian', 'j-dance', 'j-idol', 'j-pop', 'j-rock', 'jazz', 'k-pop', 'kids', 'latin', 'latino', 'malay', 'mandopop', 'metal', 'metal-misc', 'metalcore', 'minimal-techno', 'movies', 'mpb', 'new-age', 'new-release', 'opera', 'pagode', 'party', 'philippines-opm', 'piano', 'pop', 'pop-film', 'post-dubstep', 'power-pop', 'progressive-house', 'psych-rock', 'punk', 'punk-rock', 'r-n-b', 'rainy-day', 'reggae', 'reggaeton', 'road-trip', 'rock', 'rock-n-roll', 'rockabilly', 'romance', 'sad', 'salsa', 'samba', 'sertanejo', 'show-tunes', 'singer-songwriter', 'ska', 'sleep', 'songwriter', 'soul', 'soundtracks', 'spanish', 'study', 'summer', 'swedish', 'synth-pop', 'tango', 'techno', 'trance', 'trip-hop', 'turkish', 'work-out', 'world-music']
------------------------ 10 Songs of dance ----------------------------

,id,name,genre,artists,album,popularity,duration_ms,explicit
1050,2XU0oxnq2qxCpomAAuJY8K,Dance Monkey,dance,Tones And I,Dance Monkey (Stripped Back) / Dance Monkey,69,209438,False
1051,1vYXt7VSjH9JIM5oRRo7vA,Dance The Night - From Barbie The Album,dance,Dua Lipa,Dance The Night (From Barbie The Album),79,176579,False
1052,11C4y2Yz1XbHmaQwO06s9f,Dance The Night,dance,Dua Lipa,Barbie The Album,67,176579,False
1053,0a7BloCiNzLDD9qSQHh5m7,"Dance, Dance",dance,Fall Out Boy,From Under The Cork Tree,73,180266,False
1054,4LCzEYKPFcd2FCOmZdVDnM,Dance With The Devil,dance,Immortal Technique,"Revolutionary, Vol. 1",56,579293,True
1055,2g3vpJiqwswGJbUOSkCWqC,Dance Her Home,dance,Cody Johnson,Cowboy Like Me,67,174680,False
1056,0L7VCT0HOpJXBN7vadhkiU,Dance Alone,dance,"Sia, Kylie Minogue",Summer Dance Party,0,172246,False
1057,6iCX17mrswsT0QgOclgqy3,Dance Monkey,dance,Kidz Bop Kids,KIDZ BOP Party Playlist!,52,200933,False
1058,2N8m6CYs74qQO4mjVcXO30,Dance Monkey,dance,Tones And I,Welcome To The Madhouse (Deluxe),71,209438,False
1059,7cvkXf3AwPGT041PyOi5VX,Dance for You,dance,Beyoncé,4,56,377466,False

--------------------- 10 SONGS LONGER THAN AVERAGE DURATION ---------------------

,id,name,genre,artists,album,popularity,duration_ms,explicit
5,742ZnC1OgUGIScdzXEy5ui,Acoustic,acoustic,Ling tosite sigure,#4,14,238146,False
11,5Ix5RkjIO1r3gL0NH2KpqK,Acoustic,acoustic,The Re-Stoned,Plasma,8,356870,False
12,0i49QlMEbbbax1gZe2qQzm,Too Good At Goodbyes - Acoustic,acoustic,Sam Smith,Hear The Pride,0,220095,False
13,5hzQ0nwJMFTXbNZmjioxJ1,The One (Acoustic Cover),acoustic,The Moon Loungers,The One (Acoustic Cover),25,241115,False
16,1RnvWJ0pW0yhk25gQVWb3M,What If - Acoustic Sessions,acoustic,Cody Fry,Acoustic Sessions - Live From Nashville,25,245933,False
17,76QqtzlnTzVTEWhBRnDinW,Acoustic,acoustic,Mortal Treason,A Call To The Martyrs,3,213693,False
19,1Mt7cf3bZnH6UmlMrBqrVN,One (Acoustic Cover),acoustic,Girl in the Distance,One (Acoustic Cover),27,237742,False
22,1YeJ3IF2Q3JCPtkZQQrM9Q,She Will Be Loved - Acoustic,acoustic,Jonah Baker,She Will Be Loved (Acoustic),31,226698,False
24,0ElpbbncWT9aS7mgoqEHbQ,Where's My Love - Acoustic,acoustic,SYML,Where's My Love,68,239880,False
30,41DZa1qUamVuPPr7qrtbKw,Whatcha Say - Acoustic,acoustic,Jason Derulo,Heartbreaking Pop,0,222520,False

In [8]:
import pandas as pd

data_frame = pd.read_csv('spotify_tracks.csv')

genre_popularity = data_frame.groupby('genre')['popularity'].mean()

genre_popularity = genre_popularity.sort_values(ascending=False)

genre_popularity_df = genre_popularity.reset_index()

print("------------------ AVERAGE POPULARITY BY GENRE ------------------")
display(genre_popularity_df)


genre_count = data_frame.groupby('genre')['name'].count()
genre_count = genre_count.sort_values(ascending=False)
genre_count_dataframe = genre_count.reset_index()
print("----------------------- NUMBER OF SONGS BY GENRE --------------------")
display(genre_count_dataframe)

avrg_duration = data_frame.groupby('genre')['duration_ms'].mean()
avrg_duration = avrg_duration.sort_values(ascending=False)
avrg_duration_dataframe = avrg_duration.reset_index()
print("-------------------------- AVERAGE DURATION BY GENRE ----------------------------")
display(avrg_duration_dataframe)

top_songs = data_frame.groupby('genre')['popularity'].mean()
top_songs = top_songs.sort_values(ascending=False)
top_songs_datafame = top_songs.reset_index()
print("----------------------------- TOP GENRES BY POPULARITY -------------------------")
display(top_songs_datafame)
print(data_frame.columns)

------------------ AVERAGE POPULARITY BY GENRE ------------------

                 genre  popularity
0                 rock       60.34
1                dance       57.52
2                  pop       57.32
3               summer       57.06
4              country       56.50
..                 ...         ...
121     minimal-techno       12.34
122         metal-misc       11.30
123  progressive-house       10.60
124     detroit-techno       10.36
125          grindcore        9.64

[126 rows x 2 columns]

----------------------- NUMBER OF SONGS BY GENRE --------------------

           genre  name
0       acoustic    50
1       afrobeat    50
2       alt-rock    50
3    alternative    50
4        ambient    50
..           ...   ...
121       trance    50
122     trip-hop    50
123      turkish    50
124     work-out    50
125  world-music    50

[126 rows x 2 columns]

-------------------------- AVERAGE DURATION BY GENRE ----------------------------

              genre  duration_ms
0          afrobeat    315371.04
1    detroit-techno    293284.40
2             piano    284555.50
3        electronic    280711.32
4       black-metal    278538.66
..              ...          ...
121       hardstyle    150353.50
122           study    142709.70
123         ambient    141257.56
124          german    121259.42
125       grindcore    120265.78

[126 rows x 2 columns]

----------------------------- TOP GENRES BY POPULARITY -------------------------

                 genre  popularity
0                 rock       60.34
1                dance       57.52
2                  pop       57.32
3               summer       57.06
4              country       56.50
..                 ...         ...
121     minimal-techno       12.34
122         metal-misc       11.30
123  progressive-house       10.60
124     detroit-techno       10.36
125          grindcore        9.64

[126 rows x 2 columns]

Index(['id', 'name', 'genre', 'artists', 'album', 'popularity', 'duration_ms',
       'explicit'],
      dtype='object')

In [9]:
import pandas as pd
import numpy as np

data_frame = pd.read_csv("spotify_tracks.csv")

conditions = [
    data_frame["genre"].str.contains(
        "rock|grunge|guitar|metal|punk|emo", case=False, na=False
    ),
    data_frame["genre"].str.contains("pop|indie|j-idol|k-pop", case=False, na=False),
    data_frame["genre"].str.contains(
        "house|techno|dance|edm|electro|trance|disco|club|breakbeat|drum-and-bass|dubstep",
        case=False,
        na=False,
    ),
    data_frame["genre"].str.contains(
        "hip-hop|rap|r-n-b|soul|funk|groove", case=False, na=False
    ),
    data_frame["genre"].str.contains(
        "reggae|reggaeton|salsa|samba|tango|latin|latino", case=False, na=False
    ),
    data_frame["genre"].str.contains(
        "ambient|chill|sleep|study|rainy-day|piano|acoustic|classical|opera|new-age",
        case=False,
        na=False,
    ),
    data_frame["genre"].str.contains(
        "jazz|blues|gospel|folk|country|bluegrass|honky-tonk",
        case=False,
        na=False,
    ),
    data_frame["genre"].str.contains(
        "disney|children|kids|comedy|show-tunes|movies|soundtracks",
        case=False,
        na=False,
    ),
]

categories = [
    "Rock/Metal",
    "Pop/Indie",
    "Electronic/Dance",
    "Hip-Hop/R&B",
    "Latin/Reggae",
    "Ambient/Chill/Classical",
    "Jazz/Blues/Folk/Country",
    "Media/Kids/Comedy",
]

data_frame["genre_category"] = np.select(conditions, categories, default="Other/World")

data_frame.to_csv("spotify_tracks_minutes_merged.csv")